name = "sih2026"
compatibility_date = "2026-09-09"
main = "apps/api/src/index.js"

[assets]
directory = "apps/web/dist"

[[d1_databases]]
binding = "DB"
database_name = "genesis_db"
database_id = "487a2f54-bc26-4248-9f00-42e3e484d9da"
